### PR TITLE
add format options for unix, and fromnow

### PR DESCRIPTION
**Pull request by SilentCicero**

### CODE REVIEW

**Comment by SilentCicero** [comment]
- `x` = timestamp
- `X` = unixtimestamp
- `fromnow` = time from now in normal language

I added momentjs standard i18n support for the `fromnow` format option.

This way the module has unix and fromnow support of which I really need for most basic apps.

The `fromnow` method may be able to be compressed slightly, and `seconds` can be added as a feature later. Too tired right now =D

P.S. love the module

**Comment by taylorhakes** [comment]
@SilentCicero I really appreciate you doing this work. 

Please open an issue to discuss major changes in the future.  I want to make sure you don't waste your time doing something that won't be merged. I know I don't have a contributing file. I will make sure to add one soon.

I am not really sure about this pull request yet. I have to give it some thought. I definitely see the value in the functionality you added. I just have to figure out the line of what features make it in. I really value the small size of the module and am trying only to add functionality that is necessary. I don't want it to just become a Moment.js clone. There are a few formatting features that Moment.js supports that I decided to skip. For instance, the week of the year formatter. I want fecha to cover 80% of use cases. It will never work for every use case.

I want to make sure you understand I appreciate your input and work. Hopefully other people using this library will give their input as well on these features.

**Comment by ShadowState** [comment]
hey, no worries ! I understand. We don't want to feature creep the library. 

I will say this, the Unix timestamp formatters add virtually no weight and provide a really standard feature. I would say necessary. 

I can remove the `fromnow` feature, which could just be it's own npm module. The weight and size make it probably something that should be it's own concern.

Thoughs?

**Comment by SilentCicero** [comment]
I've moved from now into it's own module. But I'd really like these two formatters in fecha. If not, I do understand and no worries. Great work dude !

**Comment by SilentCicero** [comment]
Here is the package: https://github.com/SilentCicero/mininow - fromnow

**Comment by SilentCicero** [comment]
@taylorhakes any thoughts on merging? I trimmed down my commit, as I stated above I think unix is critical. Would love thoughts. Best, Nick

**Comment by taylorhakes** [comment]
Hey @SilentCicero . I gave it some thought and I don't think `x` and `X` aren't right for this library. Most of the formatters are used in conjunction with other formatters (`format('YYYY-MM-DD')`). If someone just wanted to do `format('YYYY')`, I would say just use `date.getFullYear()` don't waste your time with a library. I see timestamp as falling in the standalone category.

If `x` and `X` aren't put in, it's trivial to implement. `date.getTime()` and `Math.floor(date.getTime() / 1000)`

Another issue is having the same formatters in parse and format. The timestamp parse is pointless. The user should just use `new Date(timestamp)`

I really appreciate your work, but I have to draw the line somewhere. If you need this functionality, please feel free to fork this library and add it yourself.

**Comment by SilentCicero** [comment]
@taylorhakes okay, no worries ! I'll just use some other packages for that. Great work once again.

**Pull request closed without merging**
