### PR TITLE
Adds fecha.info() and fecha.valid() methods and tests

### PR DESCRIPTION
**Pull request by bwendt-mylo**
Finding myself needing to inspect the properties of a parsed date string quite often.

```javascript
fecha.info('1985-12-08', 'YYYY-MM-DD')
// {year: 1985, month: 11, day: 8}
```

Also useful to know if a date is valid or not.

```javascript
fecha.valid('2015-2-29', 'YYYY-MM-DD')
// false
```

### CODE REVIEW

**Comment by taylorhakes** [comment]
@bwendt-mylo I really appreciate you contributing, but in the future could you open an issue to discuss before creating a pull request? I don't want you to waste your time implementing a feature.

This is a big change and it needs some serious discussion.

Currently you can do this
```js
const date = fecha.parse('1985-12-08', 'YYYY-MM-DD');
const isValidDate = !!date;
console.log({ year: date.getFullYear(), month: date.getMonth() + 1, day: date.getDate() }): 
// {year: 1985, month: 11, day: 8}
```

Is there a compelling reason to have an `info` and `valid` function? One of the main goals of this library is to keep it as small as possible.

**Comment by bwendt-mylo** [comment]
Ah, wasn't aware that the `!!date` would work. No worries on the extra work, and in the future I will open PRs when I feel a contribution may be worthwhile. Feel free to close the PR.

**Comment by bwendt-mylo** [comment]
@taylorhakes How would you flag `2015-2-29` as invalid?

```javascript
const isValidDate = !!fecha.parse('2015-2-29', 'YYYY-MM-DD')
// true <--- should be false, there is no Feb. 29th in 2015
```

**Comment by taylorhakes** [comment]
I see what you are saying. I will add another function to detect this.

**Pull request closed without merging**
