### PR TITLE
Fix unit tests with TypeScript

### LINKED ISSUE #55: Fecha 3.0.2 breaks unit tests with TypeScript
I'm trying to migrate from fecha 2.3.3 to version 3.0.2.  For my application itself, the new version works perfectly. However, I'm not able to run any unit tests that uses fecha directly or indirectly.

I created a minimal TypeScript project for demonstrating the issue:

*src/example.ts*
```typescript
import fecha from "fecha"; // import * as fecha from "fecha" for version 2.3.3
export function output() { return fecha.format(new Date(), "YYYY"); }
```

*src/app.ts*
```typescript
import {output} from "./example";
console.log(output());
```

*src/app.test,ts*
```typescript
import {output} from "./example";
it("output", () => expect(output()).toEqual("2019"));
```

*package.json*
```json
{
	"private": true,
	"dependencies": {
		"fecha": "3.0.2"
	},
	"devDependencies": {
		"@types/jest": "23.3.12",
		"awesome-typescript-loader": "5.2.1",
		"jest": "23.6.0",
		"ts-jest": "23.10.5",
		"typescript": "3.2.2",
		"webpack": "4.28.3",
		"webpack-cli": "3.2.1"
	},
	"jest": {
		"preset": "ts-jest"
	}
}
```

*tsconfig.json*
```json
{ "include": [ "./src/" ] }
```

*webpack.config.js*
```javascript
module.exports = {
    entry: "./src/app.ts",
    output: { filename: "bundle.js" },
    resolve: { extensions: [".ts"] },
    module: { rules: [ { test: /\.ts$/, use: { loader: "awesome-typescript-loader" } } ] }
}
```

I can compile (`yarn run webpack -p`) and execute the bundle (`node ./dist/bundle.js`) successfully.

However, when I try to run the tests (`yarn run jest`), I get an error:

```
 FAIL  src/app.test.ts
  × output (7ms)

  ● output

    TypeError: Cannot read property 'format' of undefined

      1 | import fecha from "fecha";
    > 2 | export function output() { return fecha.format(new Date(), "YYYY"); }
        |                                         ^

      at Object.output (src/example.ts:2:41)
      at Object.<anonymous> (src/app.test.ts:4:27)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        2.074s, estimated 3s
Ran all test suites.
error Command failed with exit code 1.
```

The same error occurs also with other testing frameworks like Jasmine. With fecha 2.3.3, it had worked.

### PR DESCRIPTION
**Pull request by pmwmedia**
Fixes #55

### CODE REVIEW

**Comment by taylorhakes** [comment]
@pmwmedia I appreciate the PR, but this PR seems to change more than the typescript definitions. Is that a mistake? You changed the exports from ES6 module to using node specific common js

**Comment by pmwmedia** [comment]
It is not enough to change the Typescript definitions. I had also to change the export. I found two options that worked for Typescript and JavaScript: `module.exports` or named export of fecha.

**Comment by taylorhakes** [comment]
Unfortunately, I can't accept any PR that modifies the code. I am happy to change typescript definitions, but not the actual code.

I saw this answer that may help you out getting the correct definitions. https://stackoverflow.com/a/39120566

```js
declare module 'fecha' {
  interface Fecha {
    masks: Masks;
    i18n: i18nSettings;
    format(dateObj: Date | number, mask: string, i18nSettings?: i18nSettings): string;
    parse(dateStr: string, format: string, i18nSettings?: i18nSettings): Date | null;
  }
  export = Fecha
}
```

**Comment by pmwmedia** [comment]
Unfortunately, the declaring of a module doesn't help in our case. I found another solution for the TypeScript definitions file without touching the JavaScript files. However, TypeScript users have to adjust the imports from `import fecha from "fecha"` to `import * as fecha from "fecha"` , or to use named imports like `import {format} from "fecha"`. Named imports feel more TypeScript native for me.

If you accept my changes on TypeScript definitions file, I can also add a brief documentation for TypeScript users to the README.md.

**Pull request merged**
