### PR TITLE
fix ordinal day parsing

### PR DESCRIPTION
**Pull request by rhalff**
This should fix issue #15

### CODE REVIEW

**Comment by gajus** [comment]
@taylorhakes any chance of merging this and releasing a patch to NPM?

**Comment by taylorhakes** [comment]
@rhalff Thanks for doing this. The second test you wrote should return a valid date, not false. The `Do` format is not limited to 2 characters or even english letters. `Do` should be a combination of the twoDigit regex and the word regex. You can combine regexs by doing `twoDigit.source` and `word.source`

I will be able to merge it, but I won't be able to release a new version to npm. You can depend on the github release tag as a short term fix.

**Comment by rhalff** [comment]
@taylorhakes I've updated the pull request using your suggestions.

Perhaps the best fix would be to only consider valid suffixes:
https://github.com/taylorhakes/fecha/blob/master/fecha.js#L54

But this will do.

**Comment by taylorhakes** [comment]
Unfortunately there is no way to get a list of valid suffixes. The developer is allowed to define their own `Do` function, so the suffixes could be anything. 

There is a possibility that the Do function someone defines starts with a word, instead of ends with one, or doesn't even have numbers. Your change will work for most use cases though.

Can you add one more test for something like `5thNovember` and `DoMMM`? That doesn' parse. Just so it's understood that that won't work with our parsing strategy.

Thanks for doing this. I really appreciate it.

**Comment by gajus** [comment]
> There is a possibility that the Do function someone defines starts with a word, instead of ends with one, or doesn't even have numbers. Your change will work for most use cases though.

Sure there is. Just iterate `Do` function from 1 to 31 and create a list of unique values to check against.

However, this it out of scope for this PR.

**Comment by taylorhakes** [comment]
```js
function DoFn() {
    var text = "";
    var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

    for( var i=0; i < 5; i++ )
        text += possible.charAt(Math.floor(Math.random() * possible.length));

    return text;
}
```

Unlikely, but gave developers the power.

**Comment by gajus** [comment]
> Unlikely, but gave developers the power.

How is this different from worrying that a user of the library will have `DoFn` as:

```js
function DoFn () { while (true) { Math.random() } }
```

and how is this your concern?

**Comment by rhalff** [comment]
@taylorhakes 

> There is a possibility that the Do function someone defines starts with a word, instead of ends with one, or doesn't even have numbers.

The new combined regexp will not match if `Do` does **not** start with a number, for that to work I should just use the `word` regexp, without prepending the twoDigit `\d\d?` regexp.

> Can you add one more test for something like 5thNov and DoMMM? That doesn't parse. Just so it's understood that that won't work with our parsing strategy.

It **does** parse because the token regexp allows it:
```js
'DoMMM'.match(/d{1,4}|M{1,4}|YY(?:YY)?|S{1,3}|Do|ZZ|([HhMsDm])\1?|[aA]|"[^"]*"|'[^']*'/g)
["Do", "MMM"]
```
Which seems like correct  behavior to me.

**Comment by taylorhakes** [comment]
I think the current regex is fine. `parseInt` only works when the string starts with a number.

Just noticed a bug. `parseInt` always needs a radix specified as the second argument. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt

**Comment by taylorhakes** [comment]
This has been fix in https://github.com/taylorhakes/fecha/commit/4fe153613340add91e2a353a8e6d4dee25c4d097 . Thanks for your help.

**Pull request closed without merging**
